# For more information, see:
# https://github.com/github/super-linter

name: Lint Code Base
on:
  pull_request:
permissions: read-all

jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v6
        env:
          LINTER_RULES_PATH: /
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_NATURAL_LANGUAGE: false
          VALIDATE_OPENAPI: false
          VALIDATE_JSCPD: false
          VALIDATE_GO: false
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}