name: Tests
on:
  pull_request:
  push:
    branches:
      - main
permissions: read-all

jobs:
  test-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            requirements.txt
            **.py
            **.yml
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip" # caching pip dependencies
        if: env.GIT_DIFF
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        if: env.GIT_DIFF
      - name: Run Tests
        run: |
          make test
        if: env.GIT_DIFF